name: Test Coveralls

on:
  push:
    branches: [ "main" ]

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests with code coverage
      run: |
        dotnet test ./QueryUrlParams.sln \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults \
          --verbosity normal

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    
    - name: Generate lcov report
      run: |
        reportgenerator \
          -reports:"./TestResults/**/coverage.cobertura.xml" \
          -targetdir:"./CoverageReport" \
          -reporttypes:lcov

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        path-to-lcov: ./CoverageReport/lcov.info
