name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  build-pack-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Generator Project
      run: dotnet build ./src/QueryUrlParamsGenerator/QueryUrlParamsGenerator.csproj --configuration Release

    - name: Restore dependencies for Main Project
      run: dotnet restore ./src/QueryUrlParams/QueryUrlParams.csproj

    - name: Build Main Project
      run: dotnet build ./src/QueryUrlParams/QueryUrlParams.csproj --configuration Release --no-restore

    - name: Pack Main Project
      run: dotnet pack ./src/QueryUrlParams/QueryUrlParams.csproj --configuration Release --no-build --output ./nupkgs

    - name: Push to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
